name: finki-hub-discord-bot

networks:
  finki_stack:
    driver: bridge
    name: finki_stack
    # Set external to true to use an existing network
    # external: true

services:
  bot:
    environment:
      API_KEY: ${API_KEY}
      APPLICATION_ID: ${APPLICATION_ID}
      CHATBOT_URL: ${CHATBOT_URL}
      DATA_STORAGE_URL: ${DATA_STORAGE_URL}
      TOKEN: ${TOKEN}
      TZ: ${TZ}
    image: ghcr.io/finki-hub/discord-bot:latest
    networks:
      - finki_stack
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
