name: finki-discord-bot

services:
  bot:
    environment:
      TOKEN: ${TOKEN}
      APPLICATION_ID: ${APPLICATION_ID}
      CHATBOT_URL: ${CHATBOT_URL}
      API_KEY: ${API_KEY}
      TZ: ${TZ}
    image: ghcr.io/finki-hub/finki-discord-bot:latest
    networks:
      - finki_stack
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./sessions:/app/sessions
      - ./logs:/app/logs

networks:
  finki_stack:
    name: finki_stack
    driver: bridge
    # Set external to true to use an existing network
    # external: true
